---
# Install arp scan

- name: command check
  import_role:
    name: util/command_check
  vars:
    command_name: arp-scan

- name: installation process
  when: result.failed

  block:
  - name: update apt caches (arp-scan)
    apt:
      update_cache: yes

  - name: install dependencies (arp-scan)
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - autoconf
      - libpcap-dev

  - name: generate temp folder (arp-scan)
    tempfile:
      state: directory
      prefix: arp-scan
    register: tmp_dir

  - name: clone repository (arp-scan)
    git:
      repo: https://github.com/royhills/arp-scan.git 
      dest: "{{ tmp_dir.path }}"

  - name: installation (arp-scan)
    shell: autoreconf --install && ./configure && make && make install
    args:
      chdir: "{{ tmp_dir.path }}"

