---

# Install default
# commands need sudo
- hosts: local_env
  connection: local
  become: true
  tasks:
    - name: Install apt packages
      import_role:
        name: general/apt_packages
    - name: Install arp scan
      import_role:
        name: general/arp_scan
    - name: sudo task for dotfiles
      import_role: 
        name: dotfiles/sudo

- name: Import variables
  import_playbook: variables.yml

# execute by user
- hosts: local_env
  connection: local
  gather_facts: false
  become: true
  become_user: "{{ local_user_id }}"
  tasks:
    - name: Install vim bundle
      import_role:
        name: vim
    - name: clone and setup dotfiles
      import_role:
        name: dotfiles/user
