---
- name: Import variables
  import_playbook: variables.yml

- hosts: local_env
  connection: local
  become: true
  tasks:
    - name: Install fish
      import_role:
        name: samdoran.fish

- hosts: local_env
  connection: local
  gather_facts: false
  become: true
  become_user: "{{ local_user_id }}"
  tasks:
    - name: Install fisherman
      shell:
        cmd: curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
        executable: /usr/bin/fish
    - name: Install fisherman plugins
      import_role:
        name: fish
