---
- hosts: local_env
  connection: local
  gather_facts: false
  become: true
  become_user: kenji
  tasks:
    - name: set git config
      git_config:
        name: alias.tree
        scope: global
        value: "log --graph --pretty=format:'{{ tree_format }}'"
      vars:
        - tree_format: "%x09%C(auto) %h %Cgreen %ar %Creset%x09by %C(cyan ul)%an%Creset %x09%C(auto)%s %d"
