---
- hosts: local_env
  connection: local
  gather_facts: yes
  become: yes
  tasks:
    - name: Install ROS
      import_role:
        name: itnok.install_ros_ubuntu
      vars:
        install_ros_distro: "noetic"
        install_ros: "desktop-full"
