---

- name: Install plugins
  shell:
    cmd: fisher install {{ item }}
    executable: /usr/bin/fish
  with_items: "{{ plugins }}"

# - name: set shell theme
#   shell:
#     cmd: fish_config theme choose Tomorrow\ Night\ Bright
#     executable: /usr/bin/fish
